### ISSUE TITLE
Request for install instructions

### ISSUE THREAD

**Issue by crertel** [mattermost/mattermost-plugin-giphy#1]
Hello!

I'm a bit new to the Go stuff, and have hit a wall trying to get this to work (using `golang 1.12` and `golang-dep 0.5.0` via ASDF).

Anyways, is there a chance that we could get better instructions for actually setting this up?

Ideally there'd just be a release zip we could feed the web interface for Mattermost, but I figure that might not be an option--in the meantime, would you mind spilling some ink describing to a complete newbie how to build that zip?

**Comment by levb** [comment]
@crertel Thanks for logging the issue. At the moment this plugin is experimental and only works on   recent builds of master branch. For dev. builds `make deploy` should work agains a dev build of Mattermost server. I am not expecting that we'd release this plugin until after mattermost 5.10 (April 2019).

I am going to keep the issue open.

**Comment by crertel** [comment]
Thank you!

**Comment by ylluminate** [comment]
Was excited to see this outlined in the changelogs from Mattermost. We're running 5.13.1 and when I `git clone` this into the Mattermost plugins folder the system gripes about missing the binary in `plugins/mattermost-giphy-plugin/server/dist/plugin-linux-amd64`. 

So since I clearly I need to build this first, I backed it out to another folder and tried `make`. Unfortunately that fails as well.

Would really appreciate some solid installation instructions.

**Comment by levb** [comment]
We are working on obtaining a proper API key for Giphy to install and use the plugin, or a well-defined way for the customers to obtain such key. Work in progress.

**Comment by hanzei** [comment]
Closing as the plugin is not longer maintained. Please use https://github.com/moussetc/mattermost-plugin-giphy instead.
